// Centralised language definitions for the main app UI
window.TRANSLATIONS = {
  en: {
    appTitle: "Apartment Management",
    appSubtitle:
      "Manage contracts, deposits, debts and payments with ease.",
    navApartments: "Apartments",
    navTenants: "Tenants",
    navContracts: "Contracts",
    navRequests: "Requests",
    requestsTitle: "Apartment Requests",
    requestApartment: "Apartment",
    requestTenant: "Tenant",
    requestType: "Request Type",
    requestTypeContract: "Contract Request",
    requestTypeViewing: "Viewing Request",
    requestMessage: "Message",
    requestDate: "Date",
    requestStatus: "Status",
    requestStatusPending: "Pending",
    requestStatusAccepted: "Accepted",
    requestStatusRejected: "Rejected",
    accept: "Accept",
    reject: "Reject",
    confirmAcceptRequest: "Are you sure you want to accept this request?",
    confirmRejectRequest: "Are you sure you want to reject this request?",
    requestAccepted: "Request accepted successfully!",
    requestAcceptedCreateContract: "Request accepted. You can now create a contract for this tenant.",
    requestRejected: "Request rejected.",
    navPayments: "Payments",
    navExpensesGroup: "Expenses",
    navExpensesAll: "All",
    navExpensesRent: "Rent",
    navExpensesGarbage: "Garbage",
    navExpensesMaintenance: "Maintenance",
    navExpensesElectricity: "Electricity",
    navExpensesWater: "Water",
    navExpensesHeating: "Heating",
    languageLabel: "Language",
    roleLabel: "View As",
    roleAdmin: "Administrator",
    roleTenant: "Tenant",
    tenantsTitle: "Tenants",
    tenantsSubtitle: "Add new tenants and manage their details.",
    tenantFullName: "Full Name",
    tenantEmail: "Email",
    tenantPhone: "Phone",
    contractDeposit: "Contract Deposit",
    addTenant: "Add Tenant",
    apartmentsTitle: "Apartments",
    apartmentName: "Name",
    apartmentAddress: "Address",
    apartmentPhoto: "Photo",
    apartmentPhotos: "Photos",
    apartmentPhotosHint: "Or enter photo URLs separated by commas",
    photoUploadDragDrop: "Drag and drop photos here, or click to select",
    photoUploadHint: "You can select multiple photos (max 10)",
    photoUploadInvalid: "Please select image files only.",
    photoUploadMaxReached: "Maximum 10 photos allowed.",
    photoUploadLimitExceeded: "Photo limit reached. Only some photos were added.",
    apartmentStatus: "Status",
    apartmentAvailable: "Available",
    apartmentOccupied: "Occupied",
    apartmentElectricityCode: "Electricity Code",
    apartmentHeatingCode: "Heating Code",
    apartmentWaterCode: "Water Code",
    apartmentWasteCode: "Waste Code",
    addApartment: "Add Apartment",
    updateApartment: "Update Apartment",
    edit: "Edit",
    delete: "Delete",
    keep: "Keep",
    cancel: "Cancel",
    successUpdateApartment: "Apartment updated successfully!",
    confirmDeleteApartment: "Are you sure you want to delete this apartment?",
    confirmDeleteApartmentTitle: "Confirm Deletion",
    typeApartmentNameToConfirm: "Type the apartment name to confirm deletion:",
    typeApartmentNameHint: "Type \"{name}\" to confirm",
    warningDeleteApartmentWithContracts: "Warning: This apartment has contracts. Deleting it may affect related data.",
    errorDeleteApartmentWithContract: "Cannot delete apartment with active contracts. Please deactivate or end all contracts first.",
    successDeleteApartment: "Apartment deleted successfully!",
    confirmationDeleteApartment: "Are you sure you want to delete this apartment?",
    successDeleteApartment: "Apartment deleted successfully!",
    deleteIrreversible: "This action cannot be undone.",
    refresh: "Refresh",
    contractsTitle: "Contracts",
    selectApartment: "Apartment",
    selectTenant: "Tenant",
    selectContract: "Contract",
    startDate: "Start Date",
    endDate: "End Date",
    monthlyRent: "Monthly Rent",
    monthlyGarbage: "Monthly Garbage",
    monthlyMaintenance: "Monthly Maintenance",
    contractsActiveTitle: "Active contracts",
    contractsInactiveTitle: "Inactive contracts",
    contractActive: "Active",
    contractDeactivate: "Deactivate",
    contractActivate: "Activate",
    contractDeactivateBlocked:
      "Cannot deactivate contract while unpaid expenses remain.",
    successContractDeactivate: "Contract marked as inactive.",
    successContractActivate: "Contract reactivated.",
    errorInactiveContract:
      "This contract is inactive. Activate it before creating new expenses.",
    addContract: "Add Contract",
    debtsPaymentsTitle: "Debts & Payments",
    debtsPaymentsSubtitle: "Track rent, utilities, damages and more.",
    createDebt: "Create Expense",
    expenseFormToggleExpense: "Create Expense",
    expenseFormTogglePayment: "Record Payment",
    debtType: "Type",
    amount: "Amount",
    dueDate: "Due Date",
    notes: "Notes",
    createDebtButton: "Create Debt",
    updateDebtButton: "Update Expense",
    recordPayment: "Record Payment",
    selectDebt: "Debt",
    paymentDate: "Payment Date",
    paymentMethod: "Method",
    paymentReference: "Reference",
    recordPaymentButton: "Record Payment",
    updatePaymentButton: "Update Payment",
    save: "Save",
    cancelEdit: "Cancel",
    delete: "Delete",
    confirmationDeleteApartment: "Are you sure you want to delete this apartment?",
    errorDeleteApartmentWithContract: "Cannot delete apartment with active contracts. Please deactivate or end all contracts first.",
    successDeleteApartment: "Apartment deleted successfully!",
    totalLabel: "Total",
    lastPaymentDate: "Last Payment Date",
    billSingular: "bill",
    billPlural: "bills",
    unpaidExpensesSummary: "Unpaid Expenses Summary",
    expenseType: "Expense Type",
    paymentGroupInsufficient: "Enter an amount that covers at least one bill.",
    paymentGroupRemainingPrefix: "Remaining unpaid amount for",
    paymentGroupNoDebts: "No unpaid bills found for this type.",
    payRemaining: "Pay Remaining",
    paymentGroupUnusedAmountPrefix: "Unused amount not applied",
    enteredAmountLabel: "Entered",
    electricityCutLabel: "Electricity cut / disconnection",
    electricityCutNotePrefix: "Electricity is cut on",
    toggleExpenseSummary: "Tenant Summary",
    togglePaymentSummary: "Tenant Summary",
    summaryTenant: "Tenant",
    summaryExpensesCount: "Open Expenses",
    summaryExpensesAmount: "Open Amount",
    summaryPaymentsCount: "Payments",
    summaryPaymentsAmount: "Payments Amount",
    summaryNoData: "No data available.",
    paymentSummary: "Payment Summary",
    paymentSummaryPaid: "Paid",
    paymentSummaryDebt: "Expenses",
    paymentSummaryRemaining: "Remaining",
    openExpensesHeading: "Open & Overdue Expenses",
    pdfOptionsHeading: "Export Tenant PDF",
    pdfOptionEnglish: "Download in English",
    pdfOptionAlbanian: "Download in Albanian",
    pdfFormatNormal: "Normal",
    pdfFormatDetailed: "Detailed",
    filterStatus: "Status",
    filterType: "Type",
    statusAll: "All",
    statusOpenOverdue: "Open & Overdue",
    statusPaid: "Paid",
    statusOverdue: "Overdue",
    typeAll: "All",
    debtRent: "Rent",
    debtMaintenance: "Maintenance",
    debtGarbage: "Garbage",
    debtThermos: "Heating",
    debtElectricity: "Electricity",
    debtElectricityCut: "Electricity cut / disconnection",
    debtWater: "Water",
    debtDamage: "Damage",
    debtOther: "Other",
    expensesHeadingAll: "All Expenses",
    expensesHeadingRent: "Rent Expenses",
    expensesHeadingGarbage: "Garbage Expenses",
    expensesHeadingMaintenance: "Maintenance Expenses",
    expensesHeadingElectricity: "Electricity Expenses",
    expensesHeadingWater: "Water Expenses",
    expensesHeadingHeating: "Heating Expenses",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    markPaid: "Mark Paid",
    exportPdf: "Export Debts to PDF",
    paymentsHistory: "Payments History",
    loadTenant: "Load Tenant",
    tenantInfo: "Tenant Info",
    contractInfo: "Contract Info",
    financialSummary: "Financial Summary",
    overallStatistics: "Overall Statistics",
    statTenants: "Tenants",
    statApartments: "Apartments",
    statContracts: "Contracts",
    statExpenses: "Expenses",
    statPayments: "Payments",
    statTotalPayments: "Total Payments Amount",
    statTotalExpenses: "Total Expenses Amount",
    statTotalUnpaid: "Total Unpaid Expenses",
    statPdfGenerated: "PDFs Generated",
    tenantDebts: "Unpaid Expenses",
    tenantPayments: "Payments",
    exportTenantPdf: "Export to PDF",
    status: "Status",
    footerNote: "Powered by Florend Ramusa. Built for property managers and tenants.",
    profile: "Profile",
    profileTitle: "Profile",
    profileSubtitle: "View your account details and activity.",
    recentActivity: "Recent Activity",
    noRecentActivity: "No recent activity.",
    tenantSince: "Entry Date",
    totalDebt: "Total Expenses",
    totalPaid: "Total Payments",
    totalUnpaid: "Total Unpaid Expenses",
    yes: "Yes",
    no: "No",
    paid: "Paid",
    open: "Open",
    overdue: "Overdue",
    unknown: "Unknown",
    confirmationMarkPaid: "Are you sure you want to mark this debt as paid?",
    confirmationDeleteDebt: "Are you sure you want to delete this expense?",
    confirmationDeletePayment: "Are you sure you want to delete this payment?",
    successAddApartment: "Apartment created successfully.",
    successAddTenant: "Tenant created successfully.",
    successAddContract: "Contract created successfully.",
    successAddDebt: "Debt created successfully.",
    successAddPayment: "Payment recorded successfully.",
    successUpdateDebt: "Expense updated successfully.",
    successUpdatePayment: "Payment updated successfully.",
    successDeleteDebt: "Expense deleted successfully.",
    successDeletePayment: "Payment deleted successfully.",
    successMarkPaid: "Debt marked as paid.",
    errorLoad: "Something went wrong. Please try again.",
    errorFieldRequired: "Please fill all required fields.",
    errorAmountMismatch: "The amount you typed does not match. Deletion cancelled.",
    noTenantSelected: "Select a tenant to view details.",
    noDebtsFound: "No debts found.",
    noPaymentsFound: "No payments found.",
    errorAutoTableLoading:
      "PDF table plugin is loading. Please try again in a moment.",
    loginTitle: "Login",
    loginSubtitle: "Enter your credentials to access the system",
    loginButton: "Login",
    signupTitle: "Sign Up",
    signupSubtitle: "Create a new account to get started",
    signupButton: "Sign Up",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    signupLink: "Sign Up",
    loginLink: "Login",
    logout: "Logout",
    loginError: "Invalid email or password.",
    signupError: "Error creating account. Please try again.",
    passwordMismatch: "Passwords do not match.",
    loginSuccess: "Login successful!",
    signupSuccess: "Account created successfully! Please login.",
    logoutSuccess: "Logged out successfully.",
    statistics: "Statistics",
    backToDashboard: "Back to Dashboard",
    utilitySummaryTitle: "Utility Summary",
    totalExpenses: "Total Expenses:",
    totalPayments: "Total Payments:",
    difference: "Difference:",
    remainingDebt: "Remaining debt:",
    expensesList: "Expenses",
    paymentsList: "Payments",
    noData: "No data",
    directPayment: "Direct Payment",
    totalAmount: "Total Amount",
    filterByContract: "Filter by Contract:",
    allContracts: "All Contracts",
    clearFilter: "Clear",
    reference: "Reference",
    owes: "Owes",
    credit: "Credit",
    // Tenant apartments page
    tenantApartmentsTitle: "Available Apartments",
    tenantApartmentsSubtitle: "Browse apartments with photos and details, and apply for one.",
    tenantApartmentsNav: "Apartments",
    tenantContractsNav: "Contracts",
    tenantExpensesNav: "My Expenses",
    tenantProfileNav: "Profile",
    tenantLogout: "Logout",
    tenantLoadingApartments: "Loading apartments...",
    tenantFailedLoadApartments: "Failed to load apartments.",
    tenantNoApartmentsAvailable: "No apartments available at the moment.",
    tenantApplyForApartment: "Apply for this apartment",
    tenantAvailableApartments: "Available Apartments",
    tenantRequestContract: "Request Contract",
    tenantRequestViewing: "Request Viewing",
    tenantRequestContractMessage: "Requesting to create a contract for this apartment.",
    tenantRequestViewingMessage: "Requesting to view this apartment.",
    tenantRequestCreated: "Your request has been submitted successfully!",
    tenantRequestError: "Failed to create request. Please try again.",
    tenantRequestAlreadyPending: "You already have a pending request for this apartment.",
    tenantRequestAlreadyAccepted: "You already have an accepted request for this apartment.",
    // Tenant contracts page
    tenantContractsTitle: "My Contracts",
    tenantContractsSubtitle: "View your active and past rental contracts.",
    tenantActiveContracts: "Active Contracts",
    tenantPastContracts: "Past Contracts",
    tenantContractApartment: "Apartment",
    tenantContractStartDate: "Start Date",
    tenantContractEndDate: "End Date",
    tenantContractMonthlyRent: "Monthly Rent",
    tenantContractStatus: "Status",
    tenantContractActive: "Active",
    tenantContractInactive: "Inactive",
    tenantNoContracts: "None.",
    tenantNoProfileLinked: "No tenant profile linked to your email yet.",
    tenantFailedLoadContracts: "Failed to load contracts.",
    tenantNoContractsYet: "You have no contracts yet.",
    // Tenant expenses page
    tenantExpensesTitle: "My Expenses & Payments",
    tenantExpensesSubtitle: "See totals and a detailed breakdown of your expenses and payments.",
    tenantExpensesSummary: "Summary",
    tenantExpensesTotalExpenses: "Total Expenses",
    tenantExpensesTotalPayments: "Total Payments",
    tenantExpensesBalance: "Balance",
    tenantExpensesByType: "By Type",
    tenantExpensesAllExpenses: "All Expenses",
    tenantExpensesAllPayments: "All Payments",
    tenantExpensesType: "Type",
    tenantExpensesAmount: "Amount",
    tenantExpensesDueDate: "Due Date",
    tenantExpensesDate: "Date",
    tenantExpensesMethod: "Method",
    tenantExpensesStatus: "Status",
    tenantExpensesPaid: "Paid",
    tenantExpensesUnpaid: "Unpaid",
    tenantExpensesNoData: "No data yet.",
    tenantExpensesNoExpenses: "No expenses found.",
    tenantExpensesNoPayments: "No payments found.",
    tenantExpensesFailedLoad: "Failed to load data.",
    // Expense type names
    tenantExpenseTypeRent: "Rent",
    tenantExpenseTypeGarbage: "Garbage",
    tenantExpenseTypeMaintenance: "Maintenance",
    tenantExpenseTypeElectricity: "Electricity",
    tenantExpenseTypeWater: "Water",
    tenantExpenseTypeHeating: "Heating",
  },
  sq: {
    appTitle: "Menaxhimi i Banesave",
    appSubtitle:
      "Menaxhoni kontratat, depozitat, detyrimet dhe pagesat me lehtësi.",
    navApartments: "Banesat",
    navTenants: "Qeramarrësit",
    navContracts: "Kontratat",
    navRequests: "Kërkesat",
    requestsTitle: "Kërkesat për Banesa",
    requestApartment: "Banesa",
    requestTenant: "Qeramarrësi",
    requestType: "Lloji i Kërkesës",
    requestTypeContract: "Kërkesë për Kontratë",
    requestTypeViewing: "Kërkesë për Vizitë",
    requestMessage: "Mesazhi",
    requestDate: "Data",
    requestStatus: "Statusi",
    requestStatusPending: "Në Pritje",
    requestStatusAccepted: "E Pranuar",
    requestStatusRejected: "E Refuzuar",
    accept: "Prano",
    reject: "Refuzo",
    confirmAcceptRequest: "Jeni të sigurt që dëshironi të pranoni këtë kërkesë?",
    confirmRejectRequest: "Jeni të sigurt që dëshironi të refuzoni këtë kërkesë?",
    requestAccepted: "Kërkesa u pranua me sukses!",
    requestAcceptedCreateContract: "Kërkesa u pranua. Tani mund të krijoni një kontratë për këtë qeramarrës.",
    requestRejected: "Kërkesa u refuzua.",
    navPayments: "Pagesat",
    navExpensesGroup: "Shpenzimet",
    navExpensesAll: "Të Gjitha",
    navExpensesRent: "Qera",
    navExpensesGarbage: "Mbeturina",
    navExpensesMaintenance: "Mirëmbajtje",
    navExpensesElectricity: "Rrymë",
    navExpensesWater: "Ujë",
    navExpensesHeating: "Ngrohje",
    languageLabel: "Gjuha",
    roleLabel: "Shiko si",
    roleAdmin: "Administrator",
    roleTenant: "Qeramarrës",
    adminDashboard: "Paneli i Administratorit",
    tenantsTitle: "Qeramarrësit",
    tenantsSubtitle: "Shtoni qeramarrës të rinj dhe menaxhoni të dhënat e tyre.",
    tenantFullName: "Emri i Plotë",
    tenantEmail: "Email",
    tenantPhone: "Telefon",
    contractDeposit: "Depozitë Kontrate",
    addTenant: "Shto Qeramarrës",
    apartmentsTitle: "Banesat",
    apartmentName: "Emri",
    apartmentAddress: "Adresa",
    apartmentPhoto: "Foto",
    apartmentPhotos: "Foto",
    apartmentPhotosHint: "Ose vendosni URL-të e fotove të ndara me presje",
    photoUploadDragDrop: "Tërhiqni dhe lëshoni foto këtu, ose klikoni për të zgjedhur",
    photoUploadHint: "Mund të zgjidhni foto të shumta (maksimumi 10)",
    photoUploadInvalid: "Ju lutemi zgjidhni vetëm skedarë imazhi.",
    photoUploadMaxReached: "Lejohen maksimumi 10 foto.",
    photoUploadLimitExceeded: "Kufiri i fotove u arrit. Vetëm disa foto u shtuan.",
    apartmentStatus: "Statusi",
    apartmentAvailable: "E Disponueshme",
    apartmentOccupied: "E Zënë",
    apartmentElectricityCode: "Kodi i Rrymës",
    apartmentHeatingCode: "Kodi i Ngrohjes",
    apartmentWaterCode: "Kodi i Ujit",
    apartmentWasteCode: "Kodi i Mbeturinave",
    addApartment: "Shto Banesë",
    updateApartment: "Përditëso Banesën",
    edit: "Redakto",
    delete: "Fshi",
    keep: "Mbaj",
    cancel: "Anulo",
    successUpdateApartment: "Banesa u përditësua me sukses!",
    confirmDeleteApartment: "Jeni të sigurt që dëshironi të fshini këtë banesë?",
    warningDeleteApartmentWithContracts: "Paralajmërim: Kjo banesë ka kontrata. Fshirja e saj mund të ndikojë në të dhënat e lidhura.",
    errorDeleteApartmentWithContract: "Nuk mund të fshihet banesa me kontrata aktive. Ju lutemi çaktivizoni ose përfundoni të gjitha kontratat fillimisht.",
    successDeleteApartment: "Banesa u fshi me sukses!",
    confirmDeleteApartmentTitle: "Konfirmo Fshirjen",
    typeApartmentNameToConfirm: "Shkruani emrin e banesës për të konfirmuar fshirjen:",
    typeApartmentNameHint: "Shkruani \"{name}\" për të konfirmuar",
    deleteIrreversible: "Ky veprim nuk mund të zhbëhet.",
    refresh: "Rifresko",
    contractsTitle: "Kontratat",
    selectApartment: "Banesa",
    selectTenant: "Qeramarrësi",
    selectContract: "Kontrata",
    startDate: "Data e Fillimit",
    endDate: "Data e Mbarimit",
    monthlyRent: "Qeraja Mujore",
    monthlyGarbage: "Mbeturinat Mujore",
    monthlyMaintenance: "Mirëmbajtja Mujore",
    contractsActiveTitle: "Kontratat aktive",
    contractsInactiveTitle: "Kontratat joaktive",
    contractActive: "Aktive",
    contractDeactivate: "Çaktivizo",
    contractActivate: "Aktivizo",
    contractDeactivateBlocked:
      "Kontrata nuk mund të çaktivizohet derisa të shlyhen të gjitha shpenzimet.",
    successContractDeactivate: "Kontrata u çaktivizua.",
    successContractActivate: "Kontrata u riaktivizua.",
    errorInactiveContract:
      "Kjo kontratë është joaktive. Aktivizojeni para se të krijoni shpenzime të reja.",
    addContract: "Shto Kontratë",
    debtsPaymentsTitle: "Detyrimet & Pagesat",
    debtsPaymentsSubtitle: "Ndiq qeratë, shërbimet, dëmtimet dhe më shumë.",
    createDebt: "Krijo Shpenzim",
    expenseFormToggleExpense: "Krijo Shpenzim",
    expenseFormTogglePayment: "Regjistro Pagesë",
    debtType: "Lloji",
    amount: "Shuma",
    dueDate: "Afati",
    notes: "Shënime",
    createDebtButton: "Krijo Detyrim",
    updateDebtButton: "Përditëso Shpenzimin",
    recordPayment: "Regjistro Pagesë",
    selectDebt: "Detyrimi",
    paymentDate: "Data e Pagesës",
    paymentMethod: "Metoda",
    paymentReference: "Referenca",
    recordPaymentButton: "Regjistro Pagesë",
    updatePaymentButton: "Përditëso Pagesën",
    save: "Ruaj",
    cancelEdit: "Anulo",
    totalLabel: "Totali",
    lastPaymentDate: "Data e Fundit e Pagesës",
    billSingular: "faturë",
    billPlural: "fatura",
    unpaidExpensesSummary: "Përmbledhje e Shpenzimeve të Papaguara",
    expenseType: "Lloji i Shpenzimit",
    paymentGroupInsufficient:
      "Shkruani një shumë që mbulon të paktën një faturë.",
    paymentGroupRemainingPrefix: "Shuma e papaguar e mbetur për",
    paymentGroupNoDebts: "Nuk u gjetën fatura të papaguara për këtë lloj.",
    paymentGroupUnusedAmountPrefix: "Shuma e papërdorur nuk u aplikua",
    payRemaining: "Paguaj Shumën e Mbetur",
    enteredAmountLabel: "Shkruar",
    electricityCutLabel: "Ndërprerja e rrymës",
    electricityCutNotePrefix: "Rryma është ndërprerë më",
    toggleExpenseSummary: "Përmbledhje e Qeramarrësve",
    togglePaymentSummary: "Përmbledhje e Qeramarrësve",
    summaryTenant: "Qeramarrësi",
    summaryExpensesCount: "Detyrimet e Hapura",
    summaryExpensesAmount: "Shuma e Hapur",
    summaryPaymentsCount: "Nr. Pagesave",
    summaryPaymentsAmount: "Shuma e Pagesave",
    summaryNoData: "Asnjë e dhënë.",
    openExpensesHeading: "Shpenzime të Hapura & Vonesë",
    pdfOptionsHeading: "Eksporto PDF për Qeramarrësin",
    pdfOptionEnglish: "Shkarko në Anglisht",
    pdfOptionAlbanian: "Shkarko në Shqip",
    pdfFormatNormal: "Normal",
    pdfFormatDetailed: "Të Detajuara",
    filterStatus: "Statusi",
    filterType: "Lloji",
    statusAll: "Të Gjitha",
    statusOpenOverdue: "Të Hapura & Vonesë",
    statusPaid: "Të Paguara",
    statusOverdue: "Vonesë",
    typeAll: "Të Gjitha",
    debtRent: "Qera",
    debtMaintenance: "Mirëmbajtje",
    debtGarbage: "Mbeturina",
    debtThermos: "Ngrohje",
    debtElectricity: "Rrymë",
    debtElectricityCut: "Ndërprerja e rrymës",
    debtWater: "Ujë",
    debtDamage: "Dëmtim",
    debtOther: "Tjetër",
    expensesHeadingAll: "Shpenzimet Totale",
    expensesHeadingRent: "Shpenzimet e Qerasë",
    expensesHeadingGarbage: "Shpenzimet e Mbeturinave",
    expensesHeadingMaintenance: "Shpenzimet e Mirëmbajtjes",
    expensesHeadingElectricity: "Shpenzimet e Energjisë Elektrike",
    expensesHeadingWater: "Shpenzimet e Ujit",
    expensesHeadingHeating: "Shpenzimet e Ngrohjes",
    actions: "Veprimet",
    edit: "Ndrysho",
    delete: "Fshi",
    markPaid: "Shëno të Paguar",
    exportPdf: "Eksporto Detyrimet në PDF",
    paymentsHistory: "Historia e Pagesave",
    tenantDashboard: "Paneli i Qeramarrësit",
    loadTenant: "Ngarko Qeramarrësin",
    tenantInfo: "Të Dhënat e Qeramarrësit",
    contractInfo: "Të Dhënat e Kontratës",
    financialSummary: "Përmbledhje Financiare",
    overallStatistics: "Statistikat e Përgjithshme",
    statTenants: "Qeramarrësit",
    statApartments: "Banesat",
    statContracts: "Kontratat",
    statExpenses: "Shpenzimet",
    statPayments: "Pagesat",
    statTotalPayments: "Shuma e Pagesave",
    statTotalExpenses: "Shuma e Shpenzimeve",
    statTotalUnpaid: "Shuma e Papaguar",
    statPdfGenerated: "PDF të Gjeneruara",
    tenantDebts: "Shpenzime të Papaguara",
    tenantPayments: "Pagesat",
    exportTenantPdf: "Eksporto në PDF",
    status: "Statusi",
    footerNote: "Mundësohet nga Florend Ramusa. Ndërtuar për administratorë dhe qeramarrës.",
    profile: "Profili",
    profileTitle: "Profili",
    profileSubtitle: "Shiko detajet dhe aktivitetin e llogarisë.",
    recentActivity: "Aktiviteti i fundit",
    noRecentActivity: "Nuk ka aktivitet të fundit.",
    tenantSince: "Data e Hyrjes",
    totalDebt: "Shpenzime Totale",
    totalPaid: "Pagesat Totale",
    totalUnpaid: "Shpenzime të Papaguara",
    yes: "Po",
    no: "Jo",
    paid: "Paguar",
    open: "Hapur",
    overdue: "Vonesë",
    unknown: "Panjor",
    confirmationMarkPaid: "A jeni i sigurt që doni ta shënoni këtë detyrim si të paguar?",
    confirmationDeleteDebt: "A jeni i sigurt që doni ta fshini këtë shpenzim?",
    confirmationDeletePayment: "A jeni i sigurt që doni ta fshini këtë pagesë?",
    successAddApartment: "Banesa u krijua me sukses.",
    successAddTenant: "Qeramarrësi u shtua me sukses.",
    successAddContract: "Kontrata u krijua me sukses.",
    successAddDebt: "Detyrimi u krijua me sukses.",
    successAddPayment: "Pagesa u regjistrua me sukses.",
    successUpdateDebt: "Shpenzimi u përditësua me sukses.",
    successUpdatePayment: "Pagesa u përditësua me sukses.",
    successDeleteDebt: "Shpenzimi u fshi me sukses.",
    successDeletePayment: "Pagesa u fshi me sukses.",
    successMarkPaid: "Detyrimi u shënua si i paguar.",
    errorLoad: "Diçka shkoi keq. Ju lutem provoni përsëri.",
    errorFieldRequired: "Plotësoni të gjitha fushat e detyrueshme.",
    errorAmountMismatch: "Shuma që keni shkruar nuk përputhet. Fshirja u anulua.",
    noTenantSelected: "Zgjidhni një qeramarrës për të parë detajet.",
    noDebtsFound: "Asnjë detyrim i gjetur.",
    noPaymentsFound: "Asnjë pagesë e gjetur.",
    paymentSummary: "Përmbledhje Pagesash",
    paymentSummaryPaid: "E Paguar",
    paymentSummaryDebt: "Shpenzimet",
    paymentSummaryRemaining: "E Mbetur",
    errorAutoTableLoading:
      "Shtojca e tabelave për PDF po ngarkohet. Ju lutem provoni sërish pas pak.",
    loginTitle: "Hyrje",
    loginSubtitle: "Shkruani kredencialet tuaja për të hyrë në sistem",
    loginButton: "Hyr",
    signupTitle: "Regjistrohu",
    signupSubtitle: "Krijoni një llogari të re për të filluar",
    signupButton: "Regjistrohu",
    email: "Email",
    password: "Fjalëkalimi",
    confirmPassword: "Konfirmo Fjalëkalimin",
    noAccount: "Nuk keni llogari?",
    haveAccount: "Keni tashmë një llogari?",
    signupLink: "Regjistrohu",
    loginLink: "Hyr",
    logout: "Dil",
    loginError: "Email ose fjalëkalim i pavlefshëm.",
    signupError: "Gabim në krijimin e llogarisë. Ju lutem provoni përsëri.",
    passwordMismatch: "Fjalëkalimet nuk përputhen.",
    loginSuccess: "Hyrja u realizua me sukses!",
    signupSuccess: "Llogaria u krijua me sukses! Ju lutem hyni.",
    logoutSuccess: "Dilja u realizua me sukses.",
    statistics: "Statistika",
    backToDashboard: "Kthehu në Panel",
    utilitySummaryTitle: "Përmbledhja e Shërbimeve",
    totalExpenses: "Shpenzimet Totale:",
    totalPayments: "Pagesat Totale:",
    difference: "Diferenca:",
    remainingDebt: "Borxhi i mbetur:",
    expensesList: "Shpenzimet",
    paymentsList: "Pagesat",
    noData: "Nuk ka të dhëna",
    directPayment: "Pagesë Direkte",
    totalAmount: "Shuma Totale",
    filterByContract: "Filtro sipas Kontratës:",
    allContracts: "Të gjitha kontratat",
    clearFilter: "Pastro",
    reference: "Referenca",
    owes: "Ka Borxh",
    credit: "Kredi",
    // Tenant apartments page
    tenantApartmentsTitle: "Banesat e Disponueshme",
    tenantApartmentsSubtitle: "Shfletoni banesat me foto dhe detaje, dhe aplikoni për një.",
    tenantApartmentsNav: "Banesat",
    tenantContractsNav: "Kontratat",
    tenantExpensesNav: "Shpenzimet e Mia",
    tenantProfileNav: "Profili",
    tenantLogout: "Dil",
    tenantLoadingApartments: "Duke ngarkuar banesat...",
    tenantFailedLoadApartments: "Dështoi ngarkimi i banesave.",
    tenantNoApartmentsAvailable: "Nuk ka banesa të disponueshme për momentin.",
    tenantApplyForApartment: "Aplikoni për këtë banesë",
    tenantAvailableApartments: "Banesat e Disponueshme",
    tenantRequestContract: "Kërko Kontratë",
    tenantRequestViewing: "Kërko Vizitë",
    tenantRequestContractMessage: "Duke kërkuar të krijohet një kontratë për këtë banesë.",
    tenantRequestViewingMessage: "Duke kërkuar të vizitohet kjo banesë.",
    tenantRequestCreated: "Kërkesa juaj u dërgua me sukses!",
    tenantRequestError: "Dështoi krijimi i kërkesës. Ju lutemi provoni përsëri.",
    tenantRequestAlreadyPending: "Ju tashmë keni një kërkesë në pritje për këtë banesë.",
    tenantRequestAlreadyAccepted: "Ju tashmë keni një kërkesë të pranuar për këtë banesë.",
    // Tenant contracts page
    tenantContractsTitle: "Kontratat e Mia",
    tenantContractsSubtitle: "Shikoni kontratat tuaja aktive dhe të kaluara të qirasë.",
    tenantActiveContracts: "Kontratat Aktive",
    tenantPastContracts: "Kontratat e Kaluara",
    tenantContractApartment: "Banesa",
    tenantContractStartDate: "Data e Fillimit",
    tenantContractEndDate: "Data e Mbarimit",
    tenantContractMonthlyRent: "Qeraja Mujore",
    tenantContractStatus: "Statusi",
    tenantContractActive: "Aktive",
    tenantContractInactive: "Joaktive",
    tenantNoContracts: "Asnjë.",
    tenantNoProfileLinked: "Nuk ka profil qeramarrësi të lidhur me email-in tuaj ende.",
    tenantFailedLoadContracts: "Dështoi ngarkimi i kontratave.",
    tenantNoContractsYet: "Nuk keni kontrata ende.",
    // Tenant expenses page
    tenantExpensesTitle: "Shpenzimet dhe Pagesat e Mia",
    tenantExpensesSubtitle: "Shikoni totalet dhe një përmbledhje të detajuar të shpenzimeve dhe pagesave tuaja.",
    tenantExpensesSummary: "Përmbledhje",
    tenantExpensesTotalExpenses: "Shpenzimet Totale",
    tenantExpensesTotalPayments: "Pagesat Totale",
    tenantExpensesBalance: "Bilanci",
    tenantExpensesByType: "Sipas Llojit",
    tenantExpensesAllExpenses: "Të Gjitha Shpenzimet",
    tenantExpensesAllPayments: "Të Gjitha Pagesat",
    tenantExpensesType: "Lloji",
    tenantExpensesAmount: "Shuma",
    tenantExpensesDueDate: "Afati",
    tenantExpensesDate: "Data",
    tenantExpensesMethod: "Metoda",
    tenantExpensesStatus: "Statusi",
    tenantExpensesPaid: "Paguar",
    tenantExpensesUnpaid: "E Papaguar",
    tenantExpensesNoData: "Nuk ka të dhëna ende.",
    tenantExpensesNoExpenses: "Nuk u gjetën shpenzime.",
    tenantExpensesNoPayments: "Nuk u gjetën pagesa.",
    tenantExpensesFailedLoad: "Dështoi ngarkimi i të dhënave.",
    // Expense type names
    tenantExpenseTypeRent: "Qera",
    tenantExpenseTypeGarbage: "Mbeturina",
    tenantExpenseTypeMaintenance: "Mirëmbajtje",
    tenantExpenseTypeElectricity: "Rrymë",
    tenantExpenseTypeWater: "Ujë",
    tenantExpenseTypeHeating: "Ngrohje",
  },
};

// Centralised language definitions for statistics page (and can be reused elsewhere)
window.STATS_TRANSLATIONS = {
  en: {
    appTitle: "Apartment Management",
    appSubtitle: "Manage contracts, deposits, debts and payments with ease.",
    languageLabel: "Language",
    roleLabel: "View As",
    roleAdmin: "Administrator",
    roleTenant: "Tenant",
    overallStatistics: "Overall Statistics",
    myStatistics: "My Statistics",
    showOverall: "Show Overall",
    showPersonal: "Show Personal",
    statTenants: "Tenants",
    statApartments: "Apartments",
    statContracts: "Contracts",
    statExpenses: "Expenses",
    statPayments: "Payments",
    statTotalPayments: "Total Payments Amount",
    statTotalExpenses: "Total Expenses Amount",
    statTotalUnpaid: "Total Unpaid Expenses",
    statPdfGenerated: "PDFs Generated",
    utilityStatistics: "Utility Statistics",
    statElectricityExpenses: "Electricity Expenses",
    statElectricityPayments: "Electricity Payments",
    statElectricityBalance: "Electricity Balance",
    statWaterExpenses: "Water Expenses",
    statWaterPayments: "Water Payments",
    statWaterBalance: "Water Balance",
    statHeatingExpenses: "Heating Expenses",
    statHeatingPayments: "Heating Payments",
    statHeatingBalance: "Heating Balance",
    logout: "Logout",
    backToDashboard: "Back to Dashboard",
    profile: "Profile",
    footerNote: "Powered by Florend Ramusa. Built for property managers and tenants.",
  },
  sq: {
    appTitle: "Menaxhimi i Banesave",
    appSubtitle: "Menaxhoni kontratat, depozitat, detyrimet dhe pagesat me lehtësi.",
    languageLabel: "Gjuha",
    roleLabel: "Shiko si",
    roleAdmin: "Administrator",
    roleTenant: "Qeramarrës",
    overallStatistics: "Statistika e Përgjithshme",
    myStatistics: "Statistikat e Mia",
    showOverall: "Shfaq Totalin",
    showPersonal: "Shfaq Personale",
    statTenants: "Qeramarrësit",
    statApartments: "Banesat",
    statContracts: "Kontratat",
    statExpenses: "Shpenzimet",
    statPayments: "Pagesat",
    statTotalPayments: "Shuma Totale e Pagesave",
    statTotalExpenses: "Shuma Totale e Shpenzimeve",
    statTotalUnpaid: "Shpenzimet e Papaguara",
    statPdfGenerated: "PDF të Krijuara",
    utilityStatistics: "Statistikat e Shërbimeve",
    statElectricityExpenses: "Shpenzimet e Rrymës",
    statElectricityPayments: "Pagesat e Rrymës",
    statElectricityBalance: "Bilanci i Rrymës",
    statWaterExpenses: "Shpenzimet e Ujit",
    statWaterPayments: "Pagesat e Ujit",
    statWaterBalance: "Bilanci i Ujit",
    statHeatingExpenses: "Shpenzimet e Ngrohjes",
    statHeatingPayments: "Pagesat e Ngrohjes",
    statHeatingBalance: "Bilanci i Ngrohjes",
    logout: "Dil",
    backToDashboard: "Kthehu në Panel",
    profile: "Profili",
    footerNote: "Krijuar nga Florend Ramusa. Ndërtuar për menaxherët e pronave dhe qeramarrësit.",
  },
};

